# Generated by Django 6.0 on 2026-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField()),
                ("price", models.IntegerField()),
                ("product_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
