# Generated by Django 6.0 on 2026-02-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_products_delete_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="products",
            new_name="new_products",
        ),
    ]
