# Generated by Django 6.0 on 2026-02-12 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_appuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.IntegerField(
                        max_length=3,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "contact_number",
                    models.IntegerField(
                        max_length=12,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
            ],
        ),
    ]
