# Generated by Django 6.0 on 2026-02-12 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="code",
            field=models.CharField(
                max_length=3, validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_number",
            field=models.CharField(
                max_length=12,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
