# Generated by Django 6.0 on 2026-02-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_contact_code_alter_contact_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_email",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
