# Generated by Django 6.0 on 2026-02-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_contact_address_contact_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
