# Generated by Django 6.0 on 2026-02-13 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_contact_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
