# Generated by Django 6.0 on 2026-02-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_product_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
