# Generated by Django 6.0 on 2026-02-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_add_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
