# Generated by Django 6.0 on 2026-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_product_discription_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
