# Generated by Django 6.0 on 2026-02-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
