# Generated by Django 6.0.1 on 2026-03-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_alter_cart_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="user",
            new_name="name",
        ),
    ]
