# Generated by Django 6.0.1 on 2026-03-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_rename_user_cart_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="name",
            new_name="user",
        ),
    ]
