# Generated by Django 6.0 on 2026-03-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_coupon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
    ]
