# Generated by Django 6.0 on 2026-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="discription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
