# Generated by Django 6.0 on 2026-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_coupon_discription"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="min_ammount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
