# Generated by Django 6.0 on 2026-03-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_contactmsg"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmsg",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.appuser",
            ),
        ),
    ]
